import time
from src.heist_path.HeistPath import HeistPath
from src.heist_path.HeistPathA import HeistPathA


class HeistPathB(HeistPath):
    # 全新大厅到LG1办公层线路，办公层避战部分优化
    def run_path(self):
        heist_a = HeistPathA(self)
        self.goto_lg1_skip()
        self.wait_team_ui_settle()
        self.check_current_floor(1)
        self.switch_to_runner(check_switched=True)
        heist_a.lg1_wp1()
        heist_a.lg1_wp2()
        heist_a.lg1_wp3()
        self.lg1_wp4_01()
        idx = self.avoider_strategy_index()
        if idx == -1:
            self.lg1_wp4_02()
            heist_a.lg1_wp5_avoid_combat_01()
        elif idx == 0:
            self.lg1_wp5_avoid_combat_02()
        elif idx == 1:
            self.lg1_wp4_02()
            heist_a.lg1_wp5_avoid_combat_03()
        self.wait_team_ui_settle()
        self.check_current_floor(2)
        self.lg2_wp1_to_exit1()
        self.lg2_wp1_remains()
        heist_a.lg2_wp2_to_exit2()
        heist_a.lg2_wp3_to_layzer_room()
        heist_a.lg2_wp3_in_layzer_room()
        heist_a.lg2_wp4()
        if self.exit_state[1]:
            heist_a.lg2_wp4_to_exit1()
        elif self.exit_state[2]:
            heist_a.lg2_wp4_to_exit2()
        else:
            heist_a.lg2_wp4_to_exit3()

    # 全新大厅到LG1办公层线路，早雾控怪避战，理论最快11分00到办公层
    def goto_lg1_skip(self):
        self.log_round_info("寻路到LG1")
        self.sleep(0.30)
        self.switch_to_runner(check_switched=True)
        self.sleep(0.10)
        self.send_key_down("w")
        self.sleep(0.42)
        self.send_key("lshift", down_time=0.25)
        self.sleep(0.42)
        self.send_key("lshift", down_time=0.25)
        self.sleep(0.42)
        self.send_key("lshift", down_time=0.25)
        self.sleep(0.42)
        self.send_key("lshift", down_time=0.25)
        self.sleep(0.42)
        self.send_key_up("w")
        self.sleep(0.20)
        self.send_key_down("d")
        self.sleep(0.57)
        self.send_key("lshift", down_time=0.32)
        self.sleep(0.57)
        self.send_key_up("d")
        self.sleep(0.20)
        self.send_key_down("w")
        self.sleep(0.40)
        self.send_key("lshift", down_time=0.25)
        self.sleep(0.60)
        self.send_key_up("w")
        self.sleep(0.15)
        self.send_key("f", down_time=0.12)
        self.sleep(5.00)
        self.switch_to_avoider(check_switched=True)  # 切到狗哥潜行避免碰到怪改变路径
        self.sleep(0.10)
        self.send_key_down("w")
        self.sleep(0.15)
        self.send_key_down("lshift")
        self.sleep(0.24)
        self.send_key("d", down_time=0.30)
        self.sleep(1.28)
        self.send_key_up("lshift")
        self.sleep(0.64)
        self.send_key("d", down_time=0.14)
        self.sleep(0.32)
        self.send_key("a", down_time=0.26)
        self.sleep(1.14)
        self.send_key_up("w")
        self.sleep(0.10)
        self.switch_to_fighter(check_switched=True)  # 切到早雾控怪
        self.sleep(0.10)
        self.send_key("a", down_time=0.20)
        self.sleep(0.10)
        self.send_key_down("w")
        self.wait_and_interact(direction="w", is_lock=True, time_out=6.4)
        if self.find_interac():
            self.send_key("s", down_time=0.10)
            self.sleep(0.25)
            self.send_key_down("e")
            self.sleep(0.10)
            self.send_key_down("e")
            self.sleep(0.10)
            self.send_key("e", down_time=2.40)
            self.send_key_down("w")
            self.wait_and_interact(direction="w", is_lock=True, time_out=6.4)
            pass
        self.switch_to_avoider(check_switched=True)  # 切到狗哥潜行避免碰到怪改变路径
        self.sleep(0.15)
        self.send_key_down("w")
        self.sleep(0.90)
        self.send_key("a", down_time=0.90)
        self.sleep(0.90)
        self.send_key_up("w")
        self.sleep(0.10)
        self.send_key("a", down_time=3.80)
        self.sleep(0.10)
        self.send_key("s", down_time=1.20)
        self.sleep(0.10)
        self.send_key("d", down_time=2.00)
        self.sleep(0.10)
        self.send_key("s", down_time=0.06)
        self.sleep(0.10)
        self.send_key("s", down_time=0.06)
        self.sleep(0.10)
        self.click(0.50, 0.50, key="middle", down_time=0.15)
        self.sleep(0.20)
        self.send_key_down("w")
        self.sleep(0.20)
        self.send_key("lshift", down_time=1.25)
        self.sleep(0.85)
        self.send_key("d", down_time=0.40)
        self.sleep(0.35)
        self.send_key("d", down_time=0.22)
        self.sleep(0.35)
        self.send_key("d", down_time=0.35)
        self.sleep(0.64)
        self.send_key_up("w")
        self.sleep(0.30)
        self.switch_to_fighter(check_switched=True)  # 切到早雾控怪
        self.sleep(0.20)
        self.send_key("s", down_time=0.10)
        self.sleep(0.20)
        self.send_key("e", down_time=2.60)
        self.sleep(0.20)
        self.send_key("w", down_time=0.22)
        self.send_key_down("w")
        self.wait_and_interact(direction="w", is_lock=True, time_out=7.64)
        self.send_key_down("w")
        self.wait_and_interact(direction="w", is_lock=False, time_out=3.65)
        self.sleep(0.30)

    # LG1部分修改，更好的狗哥避战
    def lg1_wp4_01(self):
        self.send_key_down("d")
        self.sleep(0.11)
        self.send_key_down("s")
        self.sleep(3.31)
        self.send_key_up("s")
        self.sleep(0.12)
        self.send_key_up("d")
        self.sleep(0.11)
        self.send_key_down("a")
        self.sleep(0.31)
        self.send_key_up("a")
        self.sleep(0.11)
        self.send_key_down("w")
        self.sleep(1.50)
        self.send_key_up("w")
        self.sleep(0.11)
        self.start_interaction_watch()
        self.send_key_down("f")  # start pick
        self.sleep(0.11)
        self.send_key_down("a")
        self.sleep(0.11)
        self.send_key_up("a")
        self.sleep(1.22)
        self.stop_interaction_watch()
        self.send_key_down("w")
        self.sleep(6.58)
        self.send_key_down("d")
        self.sleep(2.62)
        self.send_key_up("d")
        self.sleep(0.11)
        self.send_key_up("w")
        self.sleep(0.11)
        self.send_key_down("a")
        self.sleep(0.31)
        self.send_key_up("a")
        self.sleep(0.32)
        self.send_key_down("w")
        self.sleep(0.21)
        self.send_key_down("space")
        self.sleep(0.06)
        self.send_key_up("space")
        self.sleep(0.31)
        self.send_key_down("space")
        self.sleep(0.06)
        self.send_key_up("space")
        self.sleep(1.30)
        self.start_interaction_watch()
        self.send_key_down("d")
        self.sleep(2.10)
        self.send_key_up("d")
        self.sleep(0.11)
        self.send_key_up("w")
        self.sleep(0.65)
        self.send_key_down("w")
        self.sleep(0.22)
        self.send_key_down("d")
        self.sleep(0.61)
        self.send_key_down("space")
        self.sleep(0.06)
        self.send_key_up("space")
        self.sleep(0.56)
        self.send_key_down("space")
        self.sleep(0.06)
        self.send_key_up("space")
        self.sleep(0.14)
        self.send_key_up("d")
        self.sleep(0.11)
        self.send_key_up("w")
        self.sleep(0.34)
        self.send_key_down("d")
        self.sleep(1.41)
        self.stop_interaction_watch()
        self.send_key_down("w")
        self.sleep(0.81)
        self.send_key_up("w")
        self.sleep(0.11)
        self.send_key_up("d")
        self.sleep(0.11)
        self.send_key_down("s")
        self.sleep(0.47)
        self.send_key_up("s")
        self.sleep(0.11)
        self.send_key_down("d")
        self.sleep(0.60)
        self.send_key_up("d")
        self.sleep(0.11)
        self.send_key_down("w")
        self.sleep(3.38)
        self.send_key_up("w")
        self.sleep(0.34)
        self.send_key_down("d")
        self.sleep(0.61)
        self.send_key_up("d")
        self.sleep(0.11)
        self.loot_safes_while_walking(direction="s", time_out=2.37)
        self.sleep(0.11)
        self.send_key_up("f")  # end pick
        self.sleep(0.10)
        self.send_key_down("d")
        self.sleep(1.33)
        self.send_key_up("d")
        self.sleep(0.12)

    def lg1_wp4_02(self):
        self.send_key_down("w")
        self.sleep(9.40)
        self.send_key_up("w")
        self.sleep(0.31)

    def lg1_wp5_avoid_combat_02(self):
        self.send_key_down("w")
        self.sleep(5.40)
        self.switch_to_avoider(check_switched=True)
        self.sleep(0.5)
        self.perform_avoidance_action()
        self.sleep(9.11)
        self.send_key_up("w")
        self.switch_to_runner(check_switched=True)
        self.sleep(0.5)
        self.wait_and_interact(is_lock=True)
        self.sleep(0.11)
        self.send_key_down("w")
        self.sleep(1.00)
        self.wait_and_interact(direction="w")

    # LG2部分修改，尝试优化一些被蚊子扫到的问题
    def lg2_wp1_to_exit1(self):
        self.sleep(0.10)
        self.switch_to_runner(check_switched=True)
        self.sleep(0.10)
        self.send_key('w', down_time=5.00)
        self.sleep(0.108)
        self.send_key_down('a')
        self.sleep(0.174)
        self.send_key('f', down_time=0.058)
        self.sleep(0.141)
        self.send_key('f', down_time=0.062)
        self.sleep(0.139)
        self.send_key('f', down_time=0.061)
        self.sleep(0.14)
        self.send_key('f', down_time=0.061)
        self.sleep(0.14)
        self.send_key('f', down_time=0.061)
        self.sleep(0.139)
        self.send_key('f', down_time=0.061)
        self.sleep(0.14)
        self.send_key('f', down_time=0.06)
        self.sleep(0.14)
        self.send_key('f', down_time=0.061)
        self.sleep(0.139)
        self.send_key('f', down_time=0.061)
        self.sleep(0.14)
        self.send_key('f', down_time=0.061)
        self.sleep(0.141)
        self.send_key('f', down_time=0.061)
        self.sleep(0.139)
        self.send_key('f', down_time=0.061)
        self.sleep(0.141)
        self.send_key('f', down_time=0.062)
        self.sleep(0.14)
        self.send_key('f', down_time=0.061)
        self.sleep(0.14)
        self.send_key('f', down_time=0.061)
        self.sleep(0.14)
        self.send_key('f', down_time=0.061)
        self.sleep(0.14)
        self.send_key('f', down_time=0.061)
        self.sleep(0.14)
        self.send_key('f', down_time=0.062)
        self.sleep(0.14)
        self.send_key('f', down_time=0.06)
        self.sleep(0.141)
        self.send_key('f', down_time=0.061)
        self.sleep(0.14)
        self.send_key('f', down_time=0.061)
        self.sleep(0.139)
        self.send_key('f', down_time=0.06)
        self.sleep(0.14)
        self.send_key('f', down_time=0.061)
        self.sleep(0.14)
        self.send_key('f', down_time=0.062)
        self.sleep(0.141)
        self.send_key('f', down_time=0.061)
        self.sleep(0.141)
        self.send_key('f', down_time=0.06)
        self.sleep(0.14)
        self.send_key('f', down_time=0.06)
        self.sleep(0.14)
        self.send_key('f', down_time=0.062)
        self.sleep(0.139)
        self.send_key('f', down_time=0.061)
        self.sleep(0.14)
        self.send_key('f', down_time=0.061)
        self.sleep(0.141)
        self.send_key('f', down_time=0.06)
        self.sleep(0.14)
        self.send_key('f', down_time=0.061)
        self.sleep(0.141)
        self.send_key('f', down_time=0.061)
        self.sleep(0.14)
        self.send_key('f', down_time=0.061)
        self.sleep(0.047)
        self.send_key_up('a')
        self.sleep(0.108)
        self.send_key('s', down_time=0.5)
        self.sleep(0.10)
        self.send_key('f', down_time=0.06)
        self.sleep(0.10)
        self.send_key_down('w')
        self.sleep(0.511)
        self.send_key('d', down_time=1.41)
        self.sleep(1.00) # 尝试优化被蚊子扫到的问题
        self.send_key_up('w')
        self.sleep(0.10)
        self.send_key('f', down_time=0.06)
        self.sleep(1.10)
        self.send_key('s', down_time=0.50)
        self.sleep(0.10)
        self.send_key('d', down_time=1.1)
        self.sleep(0.10)
        # self.send_key('w', down_time=2.35)
        # self.sleep(0.20)
        self.send_key_down("w")
        self.sleep(2.64)
        self.exit_state[1] = self.try_open_exit(direction="w")
        # self.sleep(0.5)

    def lg2_wp1_remains(self):
        self.send_key_down("w")
        self.sleep(2.10)
        self.send_key_up("w")
        self.sleep(0.11)
        self.send_key_down("f")  # start pick
        self.sleep(0.11)
        self.send_key_down("a")
        self.sleep(0.90)
        self.send_key_up("a")
        self.sleep(0.30)
        self.send_key_down("w")
        self.sleep(0.80)
        self.send_key_up("w")
        self.sleep(2.88)  # 尝试优化被蚊子扫到的问题
        self.send_key_down("d")
        self.sleep(0.62)
        self.send_key_up("d")
        self.sleep(0.11)
        self.send_key_down("w")
        self.sleep(3.06)
        self.send_key_up("w")
        self.sleep(0.11)
        self.switch_to_runner()
        self.sleep(0.11)
        self.send_key_down("a")
        self.sleep(0.81)
        self.send_key_up("a")
        self.sleep(0.30)
        self.send_key_down("d")
        self.sleep(0.2)
        self.send_key("lshift")
        self.sleep(1.43)
        self.send_key_up("d")
        self.switch_to_runner()
        self.sleep(0.11)
        self.send_key_down("w")
        self.sleep(1.01)
        self.send_key_up("w")
        self.sleep(0.18)
        self.send_key_down("d")
        self.sleep(0.70)
        self.send_key_up("d")
        self.sleep(0.12)
        self.send_key_down("s")
        self.sleep(3.02)
        self.send_key_up("s")
        self.switch_to_runner()
        self.sleep(0.72)
        self.send_key_down("s")
        self.sleep(6.36)
        self.send_key_up("s")
        self.switch_to_runner()
        self.sleep(0.11)
        self.send_key_down("d")
        self.sleep(5.05)
        self.send_key_up("d")
        self.sleep(0.23)
        self.switch_to_runner()
        self.sleep(0.01)
        self.send_key_up("f")  # end pick
        self.loot_safes_while_walking(
            direction="w", min_walk_time=0.8, time_out=1.3, hold=True, send_pick=True
        )
        self.sleep(0.10)
        self.send_key_down("space")
        self.sleep(0.13)
        self.send_key_up("space")
        self.sleep(0.17)
        self.send_key_down("space")
        self.sleep(0.13)
        self.send_key_up("space")
        self.sleep(7.46)
        self.send_key_down("d")
        self.sleep(1.31)
        self.send_key_up("d")
        self.sleep(0.11)
        self.send_key_up("w")
        self.switch_to_runner()
        self.sleep(0.14)
        self.send_key_down("s")
        self.sleep(0.22)
        self.send_key_up("s")
        self.sleep(0.11)
        self.send_key_down("d")
        self.sleep(0.81)
        self.send_key_up("d")
        self.sleep(0.11)
        self.send_key_down("w")
        self.sleep(0.71)
        self.send_key_up("w")
        self.sleep(0.30)
        self.send_key_down("d")
        self.sleep(0.72)
        self.send_key_up("d")
        self.sleep(0.11)
        self.send_key_down("s")
        self.sleep(0.90)
        self.send_key_up("s")
        self.sleep(0.11)
        self.send_key_down("d")
        self.sleep(2.02)
        self.send_key_up("d")
        self.switch_to_runner()
        self.sleep(0.30)
        self.send_key_down("a")
        self.sleep(0.60)
        self.send_key_up("a")
        self.sleep(0.11)
        self.send_key_down("s")
        self.sleep(3.26)
        self.send_key_up("s")
        self.switch_to_runner()
        self.sleep(0.11)
        self.send_key_down("d")
        self.sleep(1.01)
        self.send_key_up("d")
        self.sleep(0.11)
        self.send_key_down("s")
        self.sleep(0.51)
        self.send_key_up("s")
        self.sleep(0.29)
        self.send_key_down("a")
        self.sleep(0.61)
        self.send_key_up("a")
        self.sleep(0.11)
        self.send_key_down("s")
        self.sleep(7.12)
        self.send_key_up("s")
        self.switch_to_runner()
        self.sleep(0.12)
        self.send_key_down("w")
        self.sleep(0.51)
        self.send_key_down("d")
        self.sleep(1.44)
        self.send_key_up("d")
        self.sleep(0.91)
        self.send_key_up("w")
        self.sleep(0.30)
        self.send_key_down("d")
        self.sleep(0.72)
        self.send_key_up("d")
        self.sleep(0.11)
        self.send_key_down("s")
        self.sleep(0.61)
        self.send_key_up("s")
        self.sleep(0.11)
        self.send_key_up("f")  # end pick
        self.sleep(0.11)
